### ISSUE TITLE
Execute the plugin commands automaticly

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#100]
Is there a way to start commands like "Upload and run" from the command line?
This would be useful for creating build scripts that first compile Typescript to JS and then automatically upload them to the DOCUMENTS server.

*I guess this is more of a vscode related question...*

**Comment by bkircher** [comment]
Take a look at https://github.com/otris/node-documents-scripting. Most of the commands and features are implemented in this Node.js-only module. Accessing functionality from the command line and writing your own scripts should be pretty easy this way.

Is this helpful?

**Comment by FabianTe** [comment]
Yes, this might be one approach. Do you know how difficult it would be to integrate node-documents-scripting into a Typescript build pipeline? (Build TS -> Upload JS -> Run one specific script on the server)?

It would be less complicated for me to just call these commands from the Console somehow. I googled this for vscode in general but found nothing:

![image](https://user-images.githubusercontent.com/7669818/28958228-c74bfcc0-78f5-11e7-80ad-7cf388882997.png)

**Comment by wehrstedt** [comment]
It's actually pretty simple:

1. Add the node-documents-scripting module as a dependency
2.  Make sure the dependency is installed and transpiled
3. Upload and/or run scripts via cmd with
```
node node_modules/node-documents-scripting/out/cmd.js <upload|run> <path-to-launch.json> "<script or directory to upload/run>"
```

You can also include wildcards in your path to do a recursive upload/run. 
Take a look at the documentation of these commands [here](https://github.com/otris/node-documents-scripting/blob/0.1.3/src/cmd.ts#L23)

**Comment by tineheller** [comment]
Does this answer your question @FabianTe? can I close the issue?

**Comment by FabianTe** [comment]
Yes, thank you!
