### ISSUE TITLE
Include client context Typings file

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#101]
I'd love to see the client context's api as a Typings file, since I write the client code in vscode aswell.

**Comment by tineheller** [comment]
I'm not sure what you mean. What api exactly do you want as Typings file?

**Comment by FabianTe** [comment]
Everything that is available to you (the programmer) when you open a DOCUMENTS client in your webbrowser, open up the debug mode and the js console and enter ```documentsContext``` and hit enter.

The methods and field of this object could be documented in a Typings file. Usefull for programming Gadgets. This might not be directly plugin relevant but a thing to consider.

**Comment by tineheller** [comment]
Ok, yes I think it should be possible to generate a `d.ts` file for `documentsContext`. I will try it.

**Comment by tineheller** [comment]
I'm sorry, it's not as easy as I thought and I don't have enough time at the moment. Maybe I can try it again later.

**Comment by tineheller** [comment]
To resolve this, we need a tool that generates a TypeScript definition file from JSDoc. By now we haven't found a tool that works properly. So we think of creating one by ourselves. But this will take some time.

**Comment by FabianTe** [comment]
If you need to write one manually that you'd like to keep in this git repo (or a dedicated typings one) I'd love to contribute since I often encounter faulty declarations which I always have to correct in every project. I even started creating my own typings collection related to DOCUMENTS since this is rather annoying after doing it for the 4th time. :wink: 

Maybe you should consider https://www.npmjs.com/~types since it would be usefull to have the abillity to choose a typings file for a specific DOCUMENTS version.

**Comment by tineheller** [comment]
> since it would be usefull to have the abillity to choose a typings file for a specific DOCUMENTS version

I will create different `portalScripting.d.ts` files for different DOCUMENTS versions. Then, if you call the **Install PortalScripting Intellisense** command, you'll get the correct file if your server is running. Or you just choose the correct file from GitHub. But I don't think I want to use npm for this.

> If you need to write one manually that you'd like to keep in this git repo

Yes

> I'd love to contribute

That would be great!

**Comment by tineheller** [comment]
@FabianTe 
I'm not sure but maybe I got you wrong.
So we are creating a JSDoc template for creating `d.ts` files from JSDoc. With that template it will be possible to generate `d.ts` files automatically, if you only write a proper JSDoc documentation. The template is rather simple and maybe it can help you creating your own modules. So if you like you can contribute to this template. For now it's still in the repo of @wehrstedt but you can contribute there anyway.

https://github.com/wehrstedt/jsdoc-tsd

Some basic tags are already supported but there are still some missing, like e.g. Interfaces.

**Comment by tineheller** [comment]
I will close this issue, because the implementation to get the typings for DocumentsContext, Gadgets, etc. will rather be discussed in this repo
https://github.com/wehrstedt/jsdoc-tsd

Additional this typings will not be added as a feature to the extension but I will add them to the typings folder in this repo
https://github.com/otris/vscode-janus-debug/tree/master/portalscript/typings
when they are available.
And I will add a link to this typings in the corresponding documentation.
