### ISSUE TITLE
Option "encryptOnUpload" has troubles with umlauts

### ISSUE THREAD

**Issue by mweiss237** [otris/vscode-janus-debug#105]
If the option "vscode-janus-debug.encryptOnUpload" is true, all scripts will be encrypted when uploading to the DOCUMENTS Server. But if the script  includes "ä", "ö" or "ü", the server can't encrypt this script.
If you try to encrypt the same script directly on the DOCUMENTS Server, it works.

**Comment by tineheller** [comment]
Ok, what happens if you upload the script (including "ö") and "vscode-janus-debug.encryptOnUpload" is true? Do you get an error message?

**Comment by mweiss237** [comment]
No, I don't get any error message. If I open the script via DOCUMENTS Manager the script has been uploaded unencrypted.

**Comment by tineheller** [comment]
Could you try it again with the new version that I published yesterday? Just to be sure because I fixed an utf8 issue in this version. I cannot reproduce the problem by now.

**Comment by mweiss237** [comment]
Yes, seems to work now!
