### ISSUE TITLE
Export file types to JSON

### ISSUE THREAD

**Issue by wehrstedt** [otris/vscode-janus-debug#106]
For different modules we export file types to JSON or more specific to a script, which returns the file type as an object. 
This has the advantage that the file type is also in the repository and is version controlled. We dont use the XML representation because we implemented API functions which can recreate the file type by parseing the JSON structure.
Additionally you have the structure of the file type as a script on the documents server and can work with it (e.g, I added some functions to the linked script to check the mandatory fields of a file type).

For this purpose I implemented a grunt task which creates the portal script in two 2 steps:
1. It generates a script which exports the target file type to XML to a specific path
2. It converts the generated XML file to JSON and injects it in a script template.

The grunt tasks can be executed from the command line. It needs some adjustments to work in the extension, but the main functionality is already implemented.

**Comment by FabianTe** [comment]
I really like where this is going!

**Comment by derrohrbach** [comment]
Yesterday i implemented all the functionality for exporting to JSON in a PortalScript which can run on the documents server. This would make the addition to the VSCode extension much easier, as it essentially only needs to run one script on the server and write the results to a file. 

Imo JSON-Exports from the extension would be a really useful feature and a move in the right direction!

**Comment by tineheller** [comment]
Yes, the feature for exporting filetypes to JSON will be supported. I'm just not quite sure how...

Before I execute a script on server with the extension, I'd like to think about a general concept for executing scripts that are part of the extension but not part of the user's project. Then it will be possible to add more features like that by just adding scripts to the extension.
Actually there's only one thing to clear up. If the extension "secretly" uploads a script which is not part of the user's project, the user will be confused, if they find this script in their database. So probably the user will have to execute any kind of an *upload* command to use a feature that is supported by executing a script.

**Comment by FabianTe** [comment]
What about including these scripts in every DOCUMENTS installation in the scriptlibs folder?

**Comment by tineheller** [comment]
Well we thought about that. But then there's a dependency to the DOCUMENTS server. Including these scripts in the extension will offer much more flexibilty.

**Comment by derrohrbach** [comment]
What about uploading the PortalScript with a random name, like a GUID or something and deleting it again after the execution? This way the user would not even notice what happened!

**Comment by wehrstedt** [comment]
it's currently not possible to delete scripts 😎

**Comment by tineheller** [comment]
Yes, also thought about that, but I like secretly deleting scripts on server even less than uploading them. Additional, the functionality for deleting scripts is not availabe yet. Changes are required on server. So the feature would only be available in one of the next server versions. Not necessarily the next one because of a lack of time...

**Comment by FabianTe** [comment]
>  Changes are required on server. So the feature would only be available in one of the next server versions. Not necessarily the next one because of a lack of time...

Honestly I think this one (even though I'd love to have this feature) should not be implemented in such a "hack-y" way discussed earlier.

The extension (seen as client) should not have the responsibillity to add "features" to the server so it can communicate with said.

**Comment by tineheller** [comment]
To be honest, I still prefer to simply download the XML of the filetype. That is possible without any changes on server. And then generate the JSON from the XML with node.

**Comment by FabianTe** [comment]
Yes, I agree! Like that idea.

**Comment by derrohrbach** [comment]
So you can export XML without running a script? That also sounds like the best solution to me!

**Comment by tineheller** [comment]
We are thinking about different soloutions for this request. But very likely it won't be implemented in the ways described here. So this issue is closed for now. Maybe a new issue will be opened, after everything is clarified.

**Comment by idolum** [comment]
@tineheller Which approach do you want to take? I would like to keep this issue open so that we can discuss the Feature request. Otherwise, there is a good chance that this feature request will get lost. Or is there another issue related to this feature request?

**Comment by tineheller** [comment]
Well I think this request is important for several people, not only for VSCode users. So we are discussing about a server side soloution. Additional, the output format has to be discussed, because there are different use cases for this feature. The discussions about these things are not finished yet and probably it will take a little more time. But anyway the feature will be supported! I'm just not sure till now, if and when it will be provided by the plugin.

**Comment by derrohrbach** [comment]
Is there a place where we can see the progress of this feature? I am really waiting for this as this would have saved me another hour of work today ;) 

Do you have a redmine ticket for it or where is the current discussion happening? Maybe we should have a meeting for this feature, where every team can discuss their use cases and express their wishes.
