### ISSUE TITLE
DocFile.sync parameters not optional

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#107]
In this line the function parameters should all be optional:

https://github.com/otris/vscode-janus-debug/blob/master/portalscript/typings/portalScripting.d.ts#L3058

```ts
sync(checkHistoryFields?: boolean, notifyHitlistChange?: boolean, updateRefFields?: boolean, updateModifiedDate?: boolean): boolean;
```

**Comment by tineheller** [comment]
duplicate to #108
