### ISSUE TITLE
XMLHTTPRequest Declaration constructor wrong

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#108]
This declaration is wrong: https://github.com/otris/vscode-janus-debug/blob/master/portalscript/typings/portalScripting.d.ts#L8168

The constructor does not match the documentation:

![image](https://user-images.githubusercontent.com/7669818/29665406-345ff512-88d4-11e7-9f7e-9946e6050ca9.png)

The optional parameter of the method ```send``` is also wrong: https://github.com/otris/vscode-janus-debug/blob/master/portalscript/typings/portalScripting.d.ts#L8166

Guess the Typings generator isn't parsing optional parameters.

**Comment by tineheller** [comment]
> Guess the Typings generator isn't parsing optional parameters.

Your are right, it isn't. I will insert them. So this issue is duplicate to #107.
