### ISSUE TITLE
Debugger breakpoint

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#109]
Are breakpoints currently supported in the debugger?
I managed to launch a script from vscodes debug view and it executes but my breakpoints are ignored.
My DOCUMENTS server has JS debugging enabled and the port is the standard one (8089).

**Comment by bkircher** [comment]
> Are breakpoints currently supported in the debugger?

Of course!
> I managed to launch a script from vscodes debug view and it executes but my breakpoints are ignored.

Hmm, this sounds odd. You can set `"stopOnEntry": true` in your launch.json to automatically pause the script after launch.

What DOCUMENTS version are you using and have you enabled debugging in the .ini file?

**Comment by FabianTe** [comment]
I am using DOCUMENTS 2034 and have debugging enabled:

```ini
# Janus Debugger
JSDebugger yes
JSDebuggerPort 8089
```
This is my launch.json:
```json
"name": "Launch Script on Server",
			"request": "launch",
			"type": "janus",
			"script": "${workspaceRoot}/build/scripts/",
			"username": "...",
			"password": "...",
			"principal": "...",
			"host": "...",
			"applicationPort": 11000,
			"debuggerPort": 8089,
			"stopOnEntry": true,
			"log": {
				"fileName": "${workspaceRoot}/vscode-janus-debug-launch.log",
				"logLevel": {
					"default": "Debug"
				}
			},
			"timeout": 6000
		}
```
```stopOnEntry``` was ```true``` by default...

**Comment by bkircher** [comment]
> DOCUMENTS 2034

You're using a DOCUMENTS 5.0b. You need to get on a DOCUMENTS 5.0c at least. Sorry for that.

**Comment by FabianTe** [comment]
Okay thanks. Added that information to this wiki-page: https://github.com/otris/vscode-janus-debug/wiki/Enabling-the-Debugger-on-the-Server

**Comment by bkircher** [comment]
Thanks a lot @FabianTe
