### ISSUE TITLE
Scripts which are also in scriptlibs are not created correctly

### ISSUE THREAD

**Issue by derrohrbach** [otris/vscode-janus-debug#111]
If a script, lets call it appLibrary, is already existing in the scriptlibs directory (documents5/server/scriptlibs/**/*) and a new version of a script with the same name is going to be uploaded, it will not be created/updated correctly when uploaded by the vscode extension.

**Steps to reproduce:**
1. Install a script named appLibrary using the scriptlibs dir (Script should not show up in the manager yet, though it is importable and executeable)
2. Create another script with the same name using vscode
3. Upload using vscode
4. Notice that the script was not added to the documents database and does still not show up in the manager

If you create and upload the script manually using the manager, everything works as expected and the new version of the script is being used instead of the old one on the hard drive of the server

**Additional info:**
The eclipse extension is afaik able to upload and create the script (i am not 100% sure though)

**Comment by tineheller** [comment]
This Bug has been fixed on DOCUMENTS server. The fix will be available in version 5.0c HF1 (\#8042).
