### ISSUE TITLE
Mark scripts that have been changed

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#113]
In the Eclipse plugin scripts that were changed and differed from the uploaded version had a little start icon on their file icon to indicate that they were changed:

![image](https://user-images.githubusercontent.com/7669818/30016780-c76cdf52-9156-11e7-96a9-167af7df9936.png)

It would be useful to have this in this extension too. My workaround for now is that I keep **every** script "project" in at least a local git repo so that git will tell me when I change something:

![image](https://user-images.githubusercontent.com/7669818/30016871-2b0c0a7e-9157-11e7-9ba9-2b25c5928f95.png)

This of course only works when I make a commit only when I upload a script to the server.

**Comment by tineheller** [comment]
Yes I know that feature and actually I wanted to insert it in the extension for a long time. I only haven't found out yet how to change file and folder icons from inside the extension.

**Comment by FabianTe** [comment]
In some way it must be possible. When working with an Angular 2 project in vscode a popup opens that says something along the lines of "Angular 2 project detected. Do you want to reload vscode to show Angular 2 icons?"

Maybe it's worth looking into :wink:

**Comment by tineheller** [comment]
Ok thank you for the hint! I will have a look at it.

**Comment by tineheller** [comment]
The projekt was moved to GitLab
https://gitlab.otris.de/tools/vscode-janus-debug/issues/113
