### ISSUE TITLE
Unicode icons in output tab

### ISSUE THREAD

**Issue by roest01** [otris/vscode-janus-debug#118]
We have some unicode in our test report. I an older version of vscode-janus-debug this icons where displayed in the output tab. Currently there is a "?" only. =(

![vsqkql](https://user-images.githubusercontent.com/2870718/30691916-b5ed6e7e-9ec9-11e7-991a-da9b99432373.png)

Installed Version: 0.0.12

**Comment by tineheller** [comment]
hhm... it seems I still have any unicode symbols and characters...

<img src=https://user-images.githubusercontent.com/25297240/30797237-8927c074-a1d5-11e7-9c51-673b21af58ac.png width=250>

so don't know what to do... have I got anything wrong again?

**Comment by FabianTe** [comment]
@roest01 Are you on OSX? Maybe this could be part of the issue?

**Comment by tineheller** [comment]
@roest01 is this still a problem? I just don't think that there's anything that I can do here... So maybe we can close this issue.
