### ISSUE TITLE
Script Timestamps are not updated on DOCUMENTS server

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#126]
Hi guys,

a collegue just told me that scripts that have been changed via the extension but the timestamp on the DOCUMENTS server for when the script was edited last has not been updated.

**Comment by tineheller** [comment]
Thanks for the hint! I fixed it on server.

**Comment by FabianTe** [comment]
This also was an issue with the eclipse plugin. Maybe this is fixed now too 😊

**Comment by tineheller** [comment]
Actually no... I'm sorry
