### ISSUE TITLE
encryptOnUpload has no effect

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#129]
The setting ```vscocde-janus-debug.encryptOnUpload: false``` has no effect!
Our scripts will still be crypted when uploading them via the extension.

This should be fixed asap... :neutral_face:

**Comment by tineheller** [comment]
It's correct that this flag has no effect, if it's set to false. False is the default. And the default is, to encrypt scripts, that are encrypted on server or contain the encryption keyword.  If you don't want the scripts to be encrypted, remove the keyword or unencrypt them in manager.
I already planned to insert another flag for avoiding encryption of scripts that are encrypted on server and scripts that contain the encryption keyword.
Sorry for bad documentation. I will change it.

**Comment by FabianTe** [comment]
Okay, I get that.

This wouldn’t be the behavior I expected but I guess we will do with it.

For our development process this isn’t the most satisfying option though, since we would like to have no crypted scripts in development and then create a release which should have all scripts encrypted that contain #crypt.

The way it currently works we would propably have to export all unencrypted scripts to another machine, insert #crypt everywhere, crypt them and then export them as XML. :/

**Comment by FabianTe** [comment]
Where could this behaviour be changed? Is this controlled by the extension itself, the SDS Node "layer" or the DOCUMENTS server?

**Comment by tineheller** [comment]
I know it's important to have the option to keep all scripts unencrypted in any case.

It's not a big thing to add this option. Encrypting is done by the server only but it can be controlled by the extension. The server side changes are already done. I only need to add a new flag (or maybe an enum with all cases to avoid more misunderstandings...). The reason why I waited with this option is rather, that there were some problems with encryption in the beginning so I wanted to add new behaviour step by step.

The decision for the default behaviour has been made after discussing with several people with different approaches to work. I think this topic is another case where everybody seems to expect something else :) and I just try to find a way that's ok for everybody.

I think I can add and pubish this option during the next week, ok?

**Comment by FabianTe** [comment]
Thank you, that would be awesome!

Keep up the great work 😊

**Comment by tineheller** [comment]
With 2ec85b243b73d5a3509ca169dd784aebdf07f477 the new behaviour is finally added. It is available in version 0.0.28 of the extension. There is the new setting `encryptionOnUpload` with three possible values. The flag `encryptOnUpload` is deprecated. A small description about encryption will soon be added to the wiki.
