### ISSUE TITLE
Transpiling support

### ISSUE THREAD

**Issue by idolum** [otris/vscode-janus-debug#130]
We did some experiments with transpiling so that we can make use of features of ES2015 and above. So far, the outcome of these experiments seems promissing. For continuing the experiments it would be useful, if the extension supports transpiling as well, in terms of

- Before an script is uploaded to the server the script will be give to a transpiler that transpiles the script to the ES version supported by the server (ES5)
- The transpiler's output will automatically uploaded to the Server, if the transpilation was succsessful

One way to implement this could be to extend the launch.json so that

- A transpiling command can be specified. This command is executed before the upload automatically.
- An input folder or a set of input folders/files can be specified. All files of this set will be transpiled. Wildcard support would be also nice, e.g., like `input: [ "src/**.js", "test/*.js" ]`
- An optional output folder can specified. All transpiled scripts will be stored in this folder.
- The transpilation can be activated and deactivated.

The extension itself does _not_ need to provide the transpiler. The transpiler has to provided by the corresponding project via a devDependency.

**Comment by tineheller** [comment]
Could you give me an example command that you want to execute with the extension?

I just tried this:
```
$ browserify inputScript.js -o outputScript.js -t babelify
```
It is possible to execute a command like this with the extension on the terminal.
But I'm not sure how to get this command from the settings.

**Comment by tineheller** [comment]
@idolum 
According to our conversation I will provide a setting, where you can choose between two or three tanspilers (like babel...). Additional you can set some compiler options and an output folder. The input file will be the script on that the upload command is executed. The output files of the transpilation will be uploaded.

We can see later if we also want to insert something like browserify into the command for creating a single output file after transpilation.

**Comment by idolum** [comment]
@tineheller You summarized our discussion very well! 😃 In other words, the extension will wrap the transpiler and for using them you just configure the Extension by providing the needed Settings (output folder, transpiler options etc.)

**Comment by tineheller** [comment]
The project was moved to GitLab
https://gitlab.otris.de/tools/vscode-janus-debug/issues/130
