### ISSUE TITLE
JSDebugger "Launch Script on Server" not working

### ISSUE THREAD

**Issue by mweiss237** [otris/vscode-janus-debug#131]
I have trouble getting my script debugged on the Documents Server. 
My Version: DOCUMENTS Version 8045
I've inserted the script's name into launch.json like this:
`"script": "${workspaceRoot}/Test.js"`
and also added a breakpoint in my Test.js script.

Now I switch to the debugging view of VS-Code an hit the little green arrow to launch the script on the server. The Debugging-Console displays "Debugger listening on localhost:8089" but nothing happens. The vscode-janus-debug-launch.log shows this: 

```
...
DEBUG|00000.440|JanusDebugSession: done; disconnecting SDS connection
INFO |00000.440|JanusDebugSession: launchRequest: connection to localhost:8089 established. Testing...
DEBUG|00000.440|JanusDebugSession: sending InitializedEvent
INFO |00000.453|DebugConnection: handle response: {"content":{"contexts":[{"contextId":0,"contextName":"","paused":true}]},"type":"info","subtype":"contexts_list"}
DEBUG|00000.454|ContextCoordinator: handleResponse {"content":{"contexts":[{"contextId":0,"contextName":"","paused":true}]},"type":"info","subtype":"contexts_list"}
DEBUG|00000.454|ContextCoordinator: updating list of available contexts
DEBUG|00000.455|ContextCoordinator: creating new context with id: 0
INFO |00000.456|DebugConnection: handle response: {"content":{"code":1,"message":"Cannot execute debugger command."},"type":"error","contextId":0}
DEBUG|00000.456|ContextCoordinator: handleResponse {"content":{"code":1,"message":"Cannot execute debugger command."},"type":"error","contextId":0}
DEBUG|00000.458|Context: handleResponse {"content":{"code":1,"message":"Cannot execute debugger command."},"type":"error","contextId":0} for context 0
...
```

Is there anything I forgot?

**Comment by bkircher** [comment]
Hi there!

Sorry for the late reply.


> My Version: DOCUMENTS Version 8045

Can you try to determine the DOCUMENTS version using this description here: https://github.com/otris/vscode-janus-debug/wiki/FAQ#how-can-i-determine-the-documents-version-i-installed

> I've inserted the script's name into launch.json like this:
> "script": "${workspaceRoot}/Test.js
> and also added a breakpoint in my Test.js script.

This looks fine.

Also make sure you enabled debugging on the server as described here: https://github.com/otris/vscode-janus-debug/wiki/Enabling-the-Debugger-on-the-Server

Last but not least a short disclaimer: The debugger is still very experimental right now. We try to make it work reliably for the 5.0d release somewhat later this year. Until then expect all sorts of issues. That being said, hope you are successful. Have fun!
