### ISSUE TITLE
User for script execution

### ISSUE THREAD

**Issue by idolum** [otris/vscode-janus-debug#137]
If I execute a script that has not execution user assign, I get an error message:

` JavaScript error: Error in function: context.findSystemUser(): SysUser == NULL. `

To fix this, I have to go to the Documents Manager an set the execution user on the script.

But it would be nice, if I can set this user somewhere (in the configuration file?) in VS Code via the extension.

**Comment by tineheller** [comment]
When you set the flag `vscode-janus-debug.scriptParameters`, a `JSON` file is up- and downloaded together with every script. This `JSON` file contains the parameters and all attributes of the script. There is an attribute `LoginUser`. Would it be ok, if you can set the execution user there?
The attributes in the `JSON` file have no effects at the moment. But I think it's better to set them there, than to invent a new setting in configuration file. I know it's not the most user friendly though.

**Comment by idolum** [comment]
Yes! That would be perfect!

**Comment by tineheller** [comment]
It's not possible to set the Script User with the available modules.
