### ISSUE TITLE
typings directory

### ISSUE THREAD

**Issue by fiurthorn** [otris/vscode-janus-debug#139]
The typings export directory should be configurable.

**Comment by fiurthorn** [comment]
In a multi project environment the extention use the directories of the major project, not of the otris project containing the launch.config.

**Comment by FabianTe** [comment]
What about installing the typings in the folder where the user clicked in the file explorer to the left. When running the command via F1 then you have to select a folder.

**Comment by tineheller** [comment]
actually all folders that are created by the extension should be configurable

**Comment by tineheller** [comment]
The project was moved to GitLab
https://gitlab.otris.de/tools/vscode-janus-debug/issues/139
