### ISSUE TITLE
ScriptCategories root directory

### ISSUE THREAD

**Issue by fiurthorn** [otris/vscode-janus-debug#140]
We use the ScriptCategories for the separation of our solutions.

Each solution has its own directory below a `solutions` directory.

Ideally, downloading the scripts for each category creates a directory within a confi gurable directory.

**Comment by tineheller** [comment]
Yes that is planned and coming soon.

**Comment by tineheller** [comment]
> Ideally, downloading the scripts for each category creates a directory within a confi gurable directory.

Sorry, to be honest I think I didn't understand you correctly. We only planned to create subfolders for categories on download. So for now, if the **Download All** command is executed with an empty target folder, the user is asked, if subfolders should be created for the categories.

Why do you want to configure a directory? and how exactly should that behave then?

**Comment by fiurthorn** [comment]
Hi,

the following example should clarify our project construction:
```
+ PROJECT
+ webpack.json (5)
|+ solutions
\++ invoice (1)
 ||+ excutor (2)
 ||  - runScript1.js
 ||  - runScript2.js
 ||+ exits (3)
 ||  - exit.js
 ||- SourceCode.ts (4)
 |\- SourceCode1.ts
 \+ orderConfirm
  |+ excutor
  |  - runScript1.js
  |  - runScript2.js
  |+ exits
  |  - exit.js
  |- SourceCode.ts
  \- SourceCode1.ts
```

1. Solution groupping
1. Protalscripts
1. Client scripts
1. SourceCode for ths solution
   containsing exits and portalscript code
1. webpack config to resolve es6 imports

**Comment by tineheller** [comment]
Now there is an entry about the category feature in our wiki:
https://github.com/otris/vscode-janus-debug/wiki/Using-Categories-as-Subfolders
I think this should work for your project structure.

**Comment by fiurthorn** [comment]
I think that should help
