### ISSUE TITLE
Show output of "Show imports" in a new editor

### ISSUE THREAD

**Issue by wehrstedt** [otris/vscode-janus-debug#146]
Currently, the output of the command will be printed to the console.
It would be better to display the output in a temporary file which will be opened automatically,

**Comment by tineheller** [comment]
Well, when I open a file, I'll need a new filename.
So I can open the file as `scriptname.imports.js` or `scriptname.tmp.js` or open it in a new `.imports` folder...

**Comment by wehrstedt** [comment]
maybe you can use the preview-function of vs code? I don't know if there is any possiblity to use the preview window for this feature

**Comment by tineheller** [comment]
I'm sorry I just found out that I can open untitled editors and it's really pretty simple :)

**Comment by tineheller** [comment]
It's only one code line and I could commit it immediately, so this will be available with the next update probably tomorrow.
