### ISSUE TITLE
Uploading of multiple selected scripts is not possible

### ISSUE THREAD

**Issue by bestmacfly** [otris/vscode-janus-debug#147]
When selecting more than one script in the folder structure, it is possible to right click and choose "Upload script". But this seems not to work, instead you have to choose Upload on the folder to upload more than one script at once.

**Comment by vnissing** [comment]
Hi all,
I've installed the vscode-debug-janus extension 1.0.34, in Decembre 2018. When I try to upload a whole Folder(right-click on folder "Upload Scripts from Folder"), I get this message:"force upload of conflict scripts failed: Source Code missing in Parameter in uploadScript()".
Does this mean the feature is not done yet? Or is this a completely different bug?

**Comment by tineheller** [comment]
> I get this message:"force upload of conflict scripts failed: Source Code missing in Parameter in uploadScript()"

actually you should get this message only, if you try to upload an empty script, could you check that? in this case you could simply add something like an empty comment to the script

**Comment by vnissing** [comment]
thanks for the quick help. one of our scripts was empty indeed.

**Comment by tineheller** [comment]
The project was moved to GitLab
https://gitlab.otris.de/tools/vscode-janus-debug/issues/147
