### ISSUE TITLE
support relative paths for command "Download file"

### ISSUE THREAD

**Issue by wehrstedt** [otris/vscode-janus-debug#149]
If you wan't to download a file, you have to type the absolute path of the folder for the file.
It would be much handier if you could pass instead relative paths (starting from the workspace root), e.g
```
./                    // equals the workspace root (or .\ for windows, I don't know the default)
src\jscript           // equals <workspaceRoot>\src\jscript
.
.
. 
```

Another problem is that if you open a file outside the workspace root, and then you start the command to download a file, the default path suggested by the extension is the folder of the external file.

**Comment by tineheller** [comment]
The project was moved to GitLab
https://gitlab.otris.de/tools/vscode-janus-debug/issues/149
