### ISSUE TITLE
Feature Request: Categorize scripts

### ISSUE THREAD

**Issue by mweitze** [otris/vscode-janus-debug#150]
Using the DocumentsManager you can categorize scripts so it would be nice to add this functionality to the remote debugger. 
Furthermore if you categorize a script on the server and upload changes using VS Code it shows an info message which tells me the script will be uploaded in a different category.

**Comment by tineheller** [comment]
I'm sorry, not sure if I understood you correctly, but isn't that what you're looking for?
https://github.com/otris/vscode-janus-debug/wiki/Categories-as-Subfolders
If the categorie is changed on upload you will get a warning if
```
"vscode-janus-debug.forceUpload": false
```
in your `settings.json`.

**Comment by mweitze** [comment]
Well, indeed this is what I was looking for. I thought you could just tag them but the folder structure makes sense.
