### ISSUE TITLE
context.returnType typings entry

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#152]
Currently the `context.returnType` looks like this:

`var returnType: string;`

I'd like to propose:

`var returnType: "html" | "showFile" | ...`

This way the possible values would be suggested.

**Comment by tineheller** [comment]
Yes, we thought about that. But there are problems with the cases `"file:filename"` and `"download:filename"` because `filename` is any filename that has to be set by the user.

**Comment by FabianTe** [comment]
Well these could be omitted in the first implementation maybe in my optinion.


Mit freundlichen Grüßen
Fabian Terstegen

________________________________

**Comment by tineheller** [comment]
This issue was moved to the new typings project
https://gitlab.otris.de/tools/portalscript-typings/issues/3
