### ISSUE TITLE
Missing typings inheritance of DOMElement

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#156]
Currently in the typings files the interface `DOMElement` does not inherit from `DOMNode` which results in missing code completion. According to the documentation this is the appropriate inheritance tree:

![image](https://user-images.githubusercontent.com/7669818/40043683-8d167886-5825-11e8-9f09-10e7b07a6d5d.png)

The fix is really easy, just add an `extends` to the interface declaration:

```typescript
/**
 * ...
 */
declare interface DOMElement extends DOMNode {
    /**
     * This property is readonly.
     */
    tagName: string;
    // ...
}
```

Same applies for the other classes / interfaces in the graph.

**Comment by tineheller** [comment]
Well.. first thanks for the hint! it is easy to add `extends` manually to the typings, but the typings are generated by [jsdoc-tsd](https://github.com/otris/jsdoc-tsd). So I created another issue (https://github.com/otris/jsdoc-tsd/issues/29) that has to be solved first. After that, I can add `@extends` to the PortalScripting JSDoc file and than the `DOMElement` will be generated correctly.

**Comment by tineheller** [comment]
Issue was moved to the new typings project
https://gitlab.otris.de/tools/portalscript-typings/issues/1
