### ISSUE TITLE
Make context object more explorable

### ISSUE THREAD

**Issue by bkircher** [otris/vscode-janus-debug#161]
For each script that is started on a DOCUMENTS server, there is a `context` object defined in the script's global environment. Since 0.0.42, some basic properties of this object are displayed to the user in VS Code's _Variables_ pane. This needs however to be improved. Also the code is pretty much hacked together and needs cleanup.

This is only relevant when debugging DOCUMENTS scripts.

**Comment by tineheller** [comment]
Is this really important? And if, which properties should be displayed? Actually all supported properties could be shown in the **Watch** section. For example, if you want to see `context.file` simply add it there. And for the unsupported properties ther is another Issue (#194).

**Comment by idolum** [comment]
At least, it will add convenience to the debugger. As you said you can add all the needed properties to the Watch section manually, but if you want to see more than one than your have to add them before you actuall can start to debug. Having all the properties will save you same time.

But I agree with your priorization as "nice-to-have", as there is a way to wath these properties.

**Comment by tineheller** [comment]
The project was moved to GitLab
https://gitlab.otris.de/tools/vscode-janus-debug/issues/161
