### ISSUE TITLE
Allow user to evaluate JS code while debugging

### ISSUE THREAD

**Issue by bkircher** [otris/vscode-janus-debug#162]
This is easily possible and was rudimentarily working already in the past, AFAIK. See `evaluate` and `evaluate2` in the code.

**Comment by FabianTe** [comment]
FYI: Sometimes this does work for me. But with many commands I get strange errors that "the expression can't be evaluated".

**Comment by tineheller** [comment]
It is possible to evaluate the code, when the types are supported by the debugger.
For the PortalScripting types, Issue #194 was created.
If anything else is missing, please create an issue for the special case.
