### ISSUE TITLE
Simple source mapping does not work

### ISSUE THREAD

**Issue by bkircher** [otris/vscode-janus-debug#163]
Make it more robust.

Source mapping breaks very often, currently even in simple cases, degrading UX to the point the debugger is unusable.

With huge JS scripts (> 40k lines) there seems to be a timing issue with the `get_source` call to the server taking longer than expected. Try to eliminate the--if I recall correctly--timeout-based synchronisation point. (Timeouts are a bad idea for synchronisation anyways.)

Make sure simple scripts with no `#import` line and simple scripts with `#import` lines are covered as well.

Before 0.0.42, a lot of test cases broke. Try to re-enable them, increase test coverage on this very important part of the code.

**Comment by tineheller** [comment]
A few problems were fixed so some more cases seem to work now when the debugger is used as described in [Launching the Debugger](https://github.com/otris/vscode-janus-debug/wiki/Launching-the-Debugger) in wiki. Issues were created for the cases that still do not work.

> With huge JS scripts (> 40k lines) there seems to be a timing issue with the get_source call to the server taking longer than expected. Try to eliminate the--if I recall correctly--timeout-based synchronisation point. (Timeouts are a bad idea for synchronisation anyways.)

We tested big projects (server source > 45k lines). We only got problems when the server source was logged three times with [node-file-log](https://github.com/otris/node-file-log). An issue was created to fix the logging problems (#178).

> Make sure simple scripts with no #import line and simple scripts with #import lines are covered as well.

We tested scripts without `#import`, with `#import "..."` and with `#import [...]`. Also we tested smaller and bigger projects.

> Before 0.0.42, a lot of test cases broke. Try to re-enable them, increase test coverage on this very important part of the code.

Most source-map tests are re-enabled. All disaabled tests are documented why they cannot work. There is a new issue (#183) for creating more tests.
