### ISSUE TITLE
typings DocFile should be a class

### ISSUE THREAD

**Issue by fiurthorn** [otris/vscode-janus-debug#168]
DocFile should be a class definition not an interface.

The interface breaks the typescript instanceof operator.

**Comment by FabianTe** [comment]
I edited your title. Please be a bit more precise with your titles and descriptions.

**Comment by fiurthorn** [comment]
My so sorry. I described the as far als i think. DocFile ist only a sample.

So *all* typedefs should written as they are. Class as class, interface as interface.

Thats I have posted.

**Comment by tineheller** [comment]
We used interfaces for all portalScripting classes that have no constructor. We will publish another version of the `portalScripting.d.ts`  where all interfaces will be abstract classes. Then the linter will show an error when the classes are instantiated but the instanceof operator should work.

**Comment by tineheller** [comment]
This issue was moved to a new typings project
https://gitlab.otris.de/tools/portalscript-typings/issues/2
