### ISSUE TITLE
Portalscript Category for require()

### ISSUE THREAD

**Issue by fiurthorn** [otris/vscode-janus-debug#169]
require() a script with category "util/lib" and the Name BigNum as require("util/lib/BigNum").

**Comment by FabianTe** [comment]
Is it just me or does this need further information? What do you mean?

**Comment by fiurthorn** [comment]
If YouTube have a Look to my transpiling support, you see I Set the PortalScriptCategory to the source directory.

This keep the original Import path and i über not to erweitern the Import require Name.

**Comment by tineheller** [comment]
So let's say, there is a portalScript with name `BigNum` and category `util/lib` on server.
When you want to require this portalScript in another portalScript on server, you have to use
```
require("BigNum");
```
It is not possible to add a path in require, like so:
```
require("util/lib/BigNum");
```
And unfortunately it will not be possible to add this feature to our require function.
Was this your request?

**Comment by fiurthorn** [comment]
fix this in the extention to rewrite the the name from `toolbox/lib/posdata` to `toolbox.lib.posdata`.

The request is to have a bigger namespace and less rename the original imports.

typescript:
``` 
import { xml2json, json2xml } from "toolbox/lib/posdata";
```

javascript:
```
var posdata_1 = require("toolbox.lib.posdata");
```
