### ISSUE TITLE
typescript definition for documents Client SDK

### ISSUE THREAD

**Issue by fiurthorn** [otris/vscode-janus-debug#170]

**Comment by tineheller** [comment]
This is coming soon!

**Comment by tineheller** [comment]
A first version is here:
https://github.com/otris/vscode-janus-debug/blob/master/portalscript/typings/documentsClientSdk.d.ts

I'm not sure but probably there are still a few problems with this typings. You can post the problems here.

**Comment by fiurthorn** [comment]
great

**Comment by tineheller** [comment]
The issue was moved to the new typings project
https://gitlab.otris.de/tools/portalscript-typings/issues/4
