### ISSUE TITLE
Missing definition of optional arguments

### ISSUE THREAD

**Issue by idolum** [otris/vscode-janus-debug#171]
The following functions have optional parameters, but the corresponding typings do not define it as optional. This causes me false negatives in VS Code.

* `context.getEnumErgValue()`: `locale` is optional
* `context.getFieldErgName()`: `locale` is optional
* `context.getFileTypeErgName()`: `locale` is optional
* `context.getRegisterErgName()`: `locale` is optional
* `context.getFoldersByName()`: `type` is optional
* `context.getXMLServer()`: `archiveServerName` is optional

**Comment by tineheller** [comment]
done with acc95367061c85b206076e79167883c8de152717
