### ISSUE TITLE
Upload and debug script does not print the script output

### ISSUE THREAD

**Issue by wehrstedt** [otris/vscode-janus-debug#181]
If you execute a script with `Run script on server` the output of the script will be printed to the console. But if you execute a script with `Upload and debug script` the output is missing

**Comment by tineheller** [comment]
The timeout in `launch.json` didn't work correctly. But it's fixed now.
So you should get the output now, if you change the timeout in launch configuration like that
```
"configurations": [
	{
		"name": "Launch Script on Server",
		"request": "launch",
		...
		"timeout": 86400000
	},
        ...
```

@wehrstedt Could you check if that works for you?

**Comment by wehrstedt** [comment]
No, it doesn't work. 

Script:
```js
var o = {
	a: "b"
};
return JSON.stringify(o);
```

Output with upload and debug:
![image](https://user-images.githubusercontent.com/27811714/46597394-36762e80-cae0-11e8-934a-a5289b4f31df.png)

Output with run script
![image](https://user-images.githubusercontent.com/27811714/46597447-63c2dc80-cae0-11e8-8d98-cbd131d7d92b.png)

**Comment by tineheller** [comment]
In version 1.0.21 at least an error message should be shown...

**Comment by tineheller** [comment]
Fixed with https://github.com/otris/node-sds/commit/2b5f9ec1912f902254be0500c861401acf319363
