### ISSUE TITLE
Variables section is empty if script contains undefined variables

### ISSUE THREAD

**Issue by tineheller** [otris/vscode-janus-debug#188]
The variables section in debug mode remains completely empty when the script contains an empty array like that
```
var a = [];
```

Problem:
An exception is thrown for that variable, but then the whole function is cancelled and the other variables are ignored.

Workaround:
After the array gets a value, like
```
a.push("1");
```
everything is fine again and all variables and values are shown. So if you step or continue to a point in your script where the array contains at least one value, you will see all variables again.

**Comment by tineheller** [comment]
The same is true for undefined variables. E.g. if there is
```
var currentFile = context.file;
```
inside the script, but `context.file` is undefined, the variables section is also completely empty. Meaning, not any variable is shown.

**Comment by wehrstedt** [comment]
```js
var arr = [null];
```
results in `could not update variablesMap: TypeError: Cannot read property 'toString' of null`

```js
var a = null;
```
results in `could not update variablesMap: TypeError: Cannot read property 'hasOwnProperty' of null`

```js
var arr = [undefined]
```

results with
![image](https://user-images.githubusercontent.com/27811714/49508534-41043880-f883-11e8-81b8-8047a540fa8e.png)
