### ISSUE TITLE
Info message when the executed script has changed

### ISSUE THREAD

**Issue by wehrstedt** [otris/vscode-janus-debug#189]
If you use "run script" to execute a script on the server, it would be nice if the extension would check if the source code of the local file is the same as the server file.

If the source code is different, the extension should show an info message. This is a pretty rare scenario, but it could save a lot of time for bug searching if you have not noticed that your local file is different than the server file.

**Comment by tineheller** [comment]
Yes we can add this info message.

Workaround for now: if you simply always use **Upload and Run Script** instead of **Run Script** then you can always be sure that the executed server source is equal to your local source.

**Comment by wehrstedt** [comment]
Good idea... You can ignore this issue unless you're bored or you have nothing else to do 😄

**Comment by tineheller** [comment]
The **Run Script** entry was replaced by **Upload and Run Script** in context menu, so an info message is not required anymore.
