### ISSUE TITLE
Breakpoints in required skripts doesnt work

### ISSUE THREAD

**Issue by wehrstedt** [otris/vscode-janus-debug#193]
If you set a breakpoint in a skript which is imported with `require`, you can't set breakpoints / the debugger does not stop at the breakpoints

**Comment by tineheller** [comment]
* In `stackTraceRequest` the debugger command `get_all_source_urls` should be used to get all available source codes. New source codes should be added as soon as they are available (using `sourceMap.getDynamicServerSource` and `sourceMap.addDynamicScript`).
* So as we can see, `sourceMap` keeps a list of dynamic scripts (dynamic script is imported using `require`).
* Additional, `sourceMap` must keep lists of static scripts. **But:** every single dynamic sctipt needs a list of static scripts. (static script is imported using `#import`).
* If this information were added, setting breakpoints in required scripts will be easier to implement.

**Comment by tineheller** [comment]
https://gitlab.otris.de/tools/vscode-janus-debug/issues/193
