### ISSUE TITLE
Evaluate nested objects

### ISSUE THREAD

**Issue by wehrstedt** [otris/vscode-janus-debug#195]
```js
var file = context.getFileById("...");
var obj = {
    myFile: file
};

file = obj.myFile;
```

If you hover over "myFile" in the last line, the variable will not be evaluated. The same result when you open the list in the variables panel. 

Here's the log:
```
DEBUG|00008.084|VariablesMap: Evaluate for variable myFile failed: {} => Evaluation exception (Error): No message.
ERROR|00008.084|JanusDebugSession: variablesRequest failed: undefined
```

The issue is probably that you have to request `obj.myFile` instead of `myFile`

**Comment by wehrstedt** [comment]
This should proberbly the same with primitive values, you don't need to create a file..

**Comment by tineheller** [comment]
yes, same problem with
```javascript
var fileTest = {
    member1: "Hello World"
};

var obj = {
    myFile: fileTest
};

file = obj.myFile;
```

**Comment by tineheller** [comment]
The project was moved
https://gitlab.otris.de/tools/vscode-janus-debug/issues/195
