### ISSUE TITLE
Wrong type of variables in the watch-panel

### ISSUE THREAD

**Issue by wehrstedt** [otris/vscode-janus-debug#196]
If you add a variable to the watch-panel, the stringified value of the variable will be displayed:
![image](https://user-images.githubusercontent.com/27811714/49934249-21e25800-fece-11e8-97d7-3ffcd3fbb9a7.png)

**Comment by tineheller** [comment]
The project was moved
https://gitlab.otris.de/tools/vscode-janus-debug/issues/196
