### ISSUE TITLE
Problems when multiple VS Code windows open

### ISSUE THREAD

**Issue by tineheller** [otris/vscode-janus-debug#198]
**Problem**
E.g. files not found, or a quick pick or warning is shown in wrong VS Code window.

**IPC Communication**
The debugger is not running in the extension host, but as a separate standalone program. So in debugger we cannot simply use the extension API like getting all workspace files or showing an input box or warning message.
To be able to use this API in debugger, we implemented IPC communication. The IPC server is running in the extension host and the debugger uses the IPC client to send requests (like 'find all workspace files' or 'show warning') to the extension.

**Problem with IPC Communication**
When more than one VS Code window is open and the vscode-janus-debug extension is active in all windows, there is an IPC server running in every window. And if you start the debugger in any window, this debugger sends requests to the IPC servers. But the IPC servers cannot recognise, if the request is from the debugger that was started in the same window or in another window.

**Fix IPC Communication**
Send an id to the debugger (like e.g. a timestamp) when it is started and use this id for the IPC communication. The id can be send to the debugger by using a 'hidden' member in `launch.json` (see this commit c481afb9fff450a57de1eba84c79f487b328cb48).

**Comment by wehrstedt** [comment]
See https://github.com/Microsoft/vscode/issues/64997#event-2033753150

**Comment by tineheller** [comment]
> See Microsoft/vscode#64997 (comment)

Yes, we can also use the `customEvent` (mentioned in comment) to send the id, I thought about that... but I think it's easier to use the `AttachRequestArguments` that are also used by the `launch.json`.
