### ISSUE TITLE
Show server file without saving

### ISSUE THREAD

**Issue by wehrstedt** [otris/vscode-janus-debug#200]
Basically the "Download Script"-command, but the script should be downloaded to a temporary script, not to the workspace.

I would suggest to implement this as a new command "Open server file" or "Open script"

**Comment by tineheller** [comment]
Command will only be added to command palette, not to context menu

**Comment by tineheller** [comment]
The project was moved to GitLab
https://gitlab.otris.de/tools/vscode-janus-debug/issues/200
