### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vizonet** [otris/vscode-janus-debug#202]
- Issue Type: `Performance`
- Extension Name: `vscode-janus-debug`
- Extension Version: `1.0.36`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Master\otris-software.vscode-janus-debug-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by tineheller** [comment]
Could you upload the `cpuprofile.txt`-file? then I could have a look at it.
If you have this problem while using the server console, please consider to turn the server console off.

**Comment by tineheller** [comment]
Issue moved to https://gitlab.otris.de/tools/vscode-janus-debug/issues/202
