### ISSUE TITLE
Gitlab Issues

### ISSUE THREAD

**Issue by fabiante** [otris/vscode-janus-debug#203]
Hey guys!

When you have migrated this project to your Gitlab Server, will we be able to create and See issues there too?

Sincerely Fabian

**Comment by tineheller** [comment]
Yes!
The project has already been migrated but actually everything should be the same (except that you need a GitLab accout, if you want to contribute or create issues).

The project:
https://gitlab.otris.de/tools/vscode-janus-debug

The Wiki:
https://gitlab.otris.de/tools/vscode-janus-debug/wikis/home

The Issues:
https://gitlab.otris.de/tools/vscode-janus-debug/issues

If anything is missing, please let us know!

The project here on GitHub will not be deleted. But all project and wiki files will be deleted and the issues will be closed after a while. Maybe some other projects ([node-documents-scripting](https://github.com/otris/node-documents-scripting) or [node-sds](https://github.com/otris/node-sds)) will be migrated too in the future.

**Comment by FabianTe** [comment]
Glad to here that!
Right now there is no registration option on the login page though.
You might want to archive the Github projects. Then they become readonly and are flagged as archived.

**Comment by tineheller** [comment]
> Right now there is no registration option on the login page though.

Well yes, I'm sorry, for now only we can create the accounts. We only need your email address.

> You might want to archive the Github projects. Then they become readonly and are flagged as archived.

Yes, maybe that's a good idea.

**Comment by tineheller** [comment]
> Right now there is no registration option on the login page though.

We'll handle this in the next days!

**Comment by FabianTe** [comment]
Thank you very much. Looking forward to it 😉

**Comment by tineheller** [comment]
Now there is a registration option on the login page. The email domains of our partners are authorised for signing-up.

When you've got an account, you can create issues. If you additional want to contribute to the project, you can request to join the project via a link inside your account.

In case of any problems (e.g. if your email domain is not yet authorised), please contact gitlab@otris.de.

Additional you still can create an issue on GitHub, then we will move it to GitLab. But then you won't be able to comment.

A description about this will also be inserted into the README.

**Comment by FabianTe** [comment]
Nice, thanks! I'll register right away.

Just an idea: Maybe you'd like to "sync" access to https://otris.software/ to gitlab. Might make sense ;)
