### ISSUE TITLE
Display server console in output channel

### ISSUE THREAD

**Issue by bkircher** [otris/vscode-janus-debug#26]
Do a 

```js
vscode.window.createOutputChannel("Server Console");
```

somewhere.

*Benefits for the user:*
User will be able to see all server output from his scripts without the need of ssh'ing into a remote server and doing a `tail -f` or connecting with Remote Console tool or something.

*Problems:*
We need to have a SDS connection open for a way longer time than just uploading or downloading scripts. Where do we get the server's address and connection credentials from? From launch.json?

**Comment by tineheller** [comment]
A few questions, because it's close to things in the scripting-extension:
1) I'm not sure about janus but on DOCUMENTS there are different types of output. So what output exactly do you want to show? It might be the same that I do, I'm working on different types of output. I think some outputs are available without an open SDS connection.
2) Is the SDS connection not open the whole debugging time?
3) Why is it a problem to have an SDS connection open for longer?

**Comment by tineheller** [comment]
Willi already did the same thing! Just as C++
So there is a C++ project that we just have to translate to Typescript. We have to consider that the connect function is different, so we need a second connect function in node-sds.

**Comment by tineheller** [comment]
The project is JSRemoteCtrl. It's in ace. And the file is "svrctrlprox.cpp".

**Comment by tineheller** [comment]
In svrctrlprox.cpp is the required connect function. Also for example a disconnect and getMessages function.

**Comment by bkircher** [comment]
Thank you @tineheller. I know, I know. I have the file open in my editor since a week or so.

**Comment by tineheller** [comment]
Well, how could I know... because yesterday you told me that you don't know if it's possible at all. With that file it's obviously possible, isn't it?

**Comment by bkircher** [comment]
> With that file it's obviously possible, isn't it?

If and only if one does understand the code. I am looking at raw TCP streams in Wireshark now to get an idea of what and why it is happening. :roll_eyes:

**Comment by bkircher** [comment]
On my way...

**Comment by bkircher** [comment]
FYI, ongoing work here https://github.com/bkircher/vscode-janus-debug/tree/server-console.
