### ISSUE TITLE
Support #importFile

### ISSUE THREAD

**Issue by bkircher** [otris/vscode-janus-debug#27]
Support debugging scripts that consist of more than one single source file.

Since JANUS-based apps are not compliant to [CommonJS](https://en.wikipedia.org/wiki/CommonJS) we need to find how JANUS's `#importFile` actually works and if DOCUMENTS is doing something different.

**Comment by bkircher** [comment]
More reading here: [commonjs.org](http://wiki.commonjs.org).

**Comment by tineheller** [comment]
I think I need the same thing and I'm finding out what DOCUMENTS is doing here.

**Comment by tineheller** [comment]
The function "PortalScript::getSourceCodeForEditor" returns the source code of the main script and the source code of any #import script inside the main script as one string. I'll insert this function call into the callOperation function on DOCUMENTS server. Then we can get the source code string with the inserted imports by callling "node-sds.callClassOperation('getSourceCodeWithImports')" or something like that.

**Comment by bkircher** [comment]
`//#import ` is working with DOCUMENTS 5.0d and 0.0.34 of the extension. If anything is missing re-open or file a new issue.
