### ISSUE TITLE
Add a nice icon

### ISSUE THREAD

**Issue by bkircher** [otris/vscode-janus-debug#31]
I already shot Stephan in marketing a mail.

**Comment by bkircher** [comment]
First suggestion is something like this:

![js](https://cloud.githubusercontent.com/assets/536464/26624679/e716b7ca-45f1-11e7-9fcb-57b38019d9a7.png)

**Comment by idolum** [comment]
Hm? Looks very generic. Could represent anything related to JavaScript.

**Comment by bkircher** [comment]
True. The orange color is DOCUMENTS5 orange, though  👍

**Comment by FabianTe** [comment]
What about the document 5 logo? Currently I'v got just this tiny one but you get the idea: ![image](https://user-images.githubusercontent.com/7669818/27339621-94429b44-55d8-11e7-9176-0c48f77337c6.png)

**Comment by tineheller** [comment]
Or a mix of both, like that:
![unbenannt](https://user-images.githubusercontent.com/25297240/27372906-74ae2fda-5666-11e7-81db-fd0fc5c570ec.jpg)

**Comment by FabianTe** [comment]
Does it have to be JS? I suppose it's means "Janus Script".
Otherwise using *PS* (Portal Script) would prevent confusing JS for "Java Script"

**Comment by bkircher** [comment]
:heart:

**Comment by tineheller** [comment]
Yes, I want that icon!

**Comment by FabianTe** [comment]
I like it too! I'd remove the dots from the bug though,when downsizing the icon they'd look weired.

**Comment by roest01** [comment]
1. corrected color to #ff6f00
2. removed dots

![janus_vsc_icon_nodot](https://user-images.githubusercontent.com/2870718/27480412-204ec75c-5818-11e7-8149-de9d0febd02f.png)

3. create green "bug" version

![janus_vsc_icon_green](https://user-images.githubusercontent.com/2870718/27480417-2fe28e9c-5818-11e7-92b8-90ee9497989b.png)

4. combined gif

![janus_vsc_icon_green](https://user-images.githubusercontent.com/2870718/27480426-383254a6-5818-11e7-95dd-556022310995.gif)

**Comment by idolum** [comment]
I would go for the "removed dot" version. The other ones look like the hypnotoad. 😉

**Comment by bkircher** [comment]
Okay, then it is decided. I'll check with marketing. They have the last word.

@roest01 Could you provide us with the image sources / vector graphics?

BTW, I am a huge fan  of hypno toad.
![giphy-downsized](https://user-images.githubusercontent.com/536464/27632215-58d3d126-5bfb-11e7-8b95-5183ec505de1.gif)

**Comment by bkircher** [comment]
Sorry guys. Marketing does not approve. No hypnotic bug. We're stuck with:

![vscode-janus-debug](https://user-images.githubusercontent.com/536464/27637150-f7026732-5c0e-11e7-8a3e-1b6e1dd98680.png)

Case closed.

**Comment by FabianTe** [comment]
![giphy](https://user-images.githubusercontent.com/7669818/27675155-2a7359e2-5ca9-11e7-8ea1-2895f269a27d.gif)

**Comment by FabianTe** [comment]
Sorry, hit the wrong button :worried:

**Comment by tineheller** [comment]
The marketing only says the icon has to be suitable to otris. If we just wait a little, we might get an icon that is a bit less boring than the simple one.

**Comment by bkircher** [comment]
Probably done in PR #60.
