### ISSUE TITLE
Add clever source mapping implementation

### ISSUE THREAD

**Issue by bkircher** [otris/vscode-janus-debug#4]
This is needed for the attach configuration.

As opposed to the launch configuration, an attach configuration is used to debug existing extensions or applications that are already installed and running on the server somehow.

Now, this gets interesting because the user has opened a VS Code folder with possibly

- none of the files,
- some of the files,
- different versions of the files,
- or all of the files but on different relative or absolute paths

The source map should allow the mapping between local and remote scripts in the best way possible. There is actually already a really simple `SourceMap` class in sourceMap.ts which just maps based on the base-name of a path.

**Comment by bkircher** [comment]
Estimated time: something between 16 and 40h

**Comment by PhilippRo** [comment]
What is the exact problem?
Is this Ticket still needed?

**Comment by bkircher** [comment]
Done with 0.0.34 release, mostly.
