### ISSUE TITLE
Script Categrories

### ISSUE THREAD

**Issue by tineheller** [otris/vscode-janus-debug#40]
Add functions for matching script categories on server with folders in workspace.

**Comment by FabianTe** [comment]
## Temporary Workaround
This works, when the portal script eclipse plugin is set to automatically update scripts upon saving
1. Check out the scripts (incl. categories) with Eclipse.
2. Open the eclipse folder in vscode and edit files as you like.
3. Open eclipse, select the project and hit `F5`. Eclipse will upload all changed scripts into the appropriate categories.

I haven't tried doing this when the eclipse plugin is set to manual uploading.
Support in vscode would still be nice to have though ;)

**Comment by tineheller** [comment]
I think you don't need eclipse to upload the scripts. If you have already created the categories on the DOCUMENTS Server, VS Code should upload the scripts to the correct category.

**Comment by FabianTe** [comment]
@tineheller No, when I change a script that was in a script category before or create a new .js file in a folder configured as script category folder via eclipse, neither of them have a script category in the DOCUMENT Manager.

**Comment by tineheller** [comment]
Ok, thanks for the info! I'll check it as soon as possible.

**Comment by tineheller** [comment]
I will add additional parameters to the functions `uploadScript` and `downloadScript` on server side. This parameters can be used to set or get the category name as `string`.
@PhilippRo After I've added this parameters, it should be easy to implement the matching between folders and categories inside the extension.

**Comment by tineheller** [comment]
The matching between categories and folders should also be implemented for subfolders (see issue #72)

**Comment by tineheller** [comment]
@PhilippRo 
I added the member `category` to the `script` type. This member can be used for the matching.
When `script.category` contains a category name on upload, the script will be assigned to this category. If the category does not exist, a new category with this name will be created.
If a script is assigned to a category on server, `script.category` will contain the category name after download.
I think with this member it should be easy now, to implement the 'folder' part of this issue. Meaning, to store the scripts in a folder with the category name after download or to set the folder name to the category before upload.

**Comment by FabianTe** [comment]
>The matching between categories and folders should also be implemented for subfolders

Consider a script in this path:

```.../Project/src/core/controller/InvoiceOnSafe.js```

I can imagine two different was this might work

1. The script is uploaded into the category ```controller```
2. The script is uploaded into the category ```core-controller``` where **-** could be some other separator .

Version 2 allows for a greater control. Image you had categories on a DOCUMENTS server like ```systemName-moduleName``` and imported them. When importing the user could say "split categories into folders based on the separator **-**.

Version 1 should be implemented anyways.
Version 2 might be overkill for now. I'll open it as a new feature request issue if so.

**Comment by tineheller** [comment]
> As you can see the uploaded script is still in the wmdx-test category but when I open it, it has no script category (yes, I refreshed the DOCUMENTS Manager). Guess this is more of a DOCUMENTS Manager bug.

@FabianTe Sorry, it took a bit longer. I just checked it. But I can't reproduce the problem. I have a script on DOCUMENTS server. And the script has a category. When I change the script in VS Code and upload it, the script is still in the category and when I open it it has a script category.
If you still have the problem, please let me know.

**Comment by FabianTe** [comment]
@tineheller I'll try to reproduce this when possible and create a new issue if it happens again. This probably isn't the proper place to discuss this.

**Comment by tineheller** [comment]
The categories on documents server only support one level. There are no subcategories. So a correct matching between the categories and folders in a file system which can contain subfolders is simply not possible. Trying to create this matching will rather end up in a bad hack.
I think a command for downloading scripts from one or more categories and creating folders with category names can be added. But not like a matching. I will create a new issue, when there's time to implement this commands.
