### ISSUE TITLE
Check DOCUMENTS version

### ISSUE THREAD

**Issue by tineheller** [otris/vscode-janus-debug#42]
The scripting part of this extension only works with a recent DOCUMENTS 5 version. So the version must be checked and in case of an old version a suitable error message must be shown.

**Comment by bkircher** [comment]
Hi @tineheller!

Could you add add a comment with the commit's SHA1 that resolves the issue when closing? (In case of multiple commits the last relevant commit is sufficient.) If there is no relevant commit, could you still leave a short comment on why you are closing the issue?

This way others are able to comprehend and follow the changes you make regarding the issue.

Thanks!

**Comment by tineheller** [comment]
Done with commit https://github.com/otris/node-documents-scripting/commit/363461d2e1ff9605dc7f1d396597ec9f81853f28
