### ISSUE TITLE
Debugger: Pause next script

### ISSUE THREAD

**Issue by bkircher** [otris/vscode-janus-debug#46]
Provide a VS Code command that orders the server to pause the next script that is going to be executed. 

After a script is started (and immediately paused), attach the debug adapter. Provide the user with two options:

* debug the script
* continue execution of that script and instead pause the next script's execution

Suggested by @christophniemann.

**Comment by bkircher** [comment]
We experiment here a little

**Comment by tineheller** [comment]
The project was moved
https://gitlab.otris.de/tools/vscode-janus-debug/issues/46
