### ISSUE TITLE
Save hashed passwords

### ISSUE THREAD

**Issue by bkircher** [otris/vscode-janus-debug#49]
## Current Situation:

Passwords are

* typically entered by the user in a dialog window anytime it is needed by the extension or
* saved by the user in in plain-text in `launch.json`.

Notice: the extension itself never saves a password to `launch.json` or anywhere else. But the user is forced to either enter his password every time he connects to the server _or_ save it once in the `launch.json` file.

## Motivation
It would be nice if we wouldn't force the user to save his clear text password to `launch.json`.

### 1) Save Hashed Password to a Separate File

The user gets a "Please enter the password:" dialog, and after successful connection is again asked if he wants to remember it. If the response is yes, the hashed password is saved to disk. A user can silence the second dialog by setting `"vscode-janus-debug.rememberPasswords: false"` in `settings.json` or something.

Only the hashed password is saved. Also the hashed password is saved to a separate file, not in `launch.json`. A separate file can be easily removed without any harm or added to `.{git,svn}ignore` file(s).

That way the `"password"` property can be removed from all debug configurations.

Problems with this approach: What if the user changes the target server in the `launch.json` and then tries to connect? He will get a authorization error. Hence, he needs to remember to additionally remove the password file. Solution to that could be to associate the hashed password with the `"host"` that it belongs to.

### Other Ideas?
Somebody?

**Comment by FabianTe** [comment]
The idea of saving the password in a hashed form seems reasonable to me.
>Problems with this approach: What if the user changes the target server in the launch.json and then tries to connect? He will get a authorization error. Hence, he needs to remember to additionally remove the password file. Solution to that could be to associate the hashed password with the "host" that it belongs to.

I get the pros of saving the password in a seperate file, but I think it would make the overall plugin usage less clear. Then you'd have the password in a file, the plugin settings in visual code's settings.json and the launch configurations.

I thought about saving connection information (credentials, hosts, etc.) in visual codes workspace's settings.json but that results in the same "problem" (not being able to `git ignore` and so on)

What about saving said information generally in `.vscode/janus-debug/...` or `.janus-debug/...`? In these folders you could save the connection configurations in one file each and still be able to ignore or include them in SCM separately.

**Comment by tineheller** [comment]
We could save the hashed passwords into the file ".vscode/.documents-scripting-cache". I already use this file to save source code hash values. And I think associating the passwords with the "host" is a good idea.

**Comment by tineheller** [comment]
The extension and the debugger both use the password stored in `launch.json`. So if the behaviour with passwords should be changed in whatever way, the debugger and the extension must be considered.

The most popular idea here is to simply save the hashed password in `launch.json`. Even though that's not really a *save* soloution...

**Comment by tineheller** [comment]
Now there's an option to avoid saving the password, this can be used, if the password shouldn't be shown.
