### ISSUE TITLE
Ctrl+S wants to upload a script

### ISSUE THREAD

**Issue by bkircher** [otris/vscode-janus-debug#50]
It seems like we "overloaded" Ctrl+S keyboard shortcut. This is highly unexpected because this is the one keyboard shortcut for saving modified files on nearly every platform out there since ages.

## Steps to reproduce

1. Make sure the extension is activated by starting a debugging session or creating a `launch.json` file or whatever. The status bar shows: "vscode-janus-debug is active" (visible in the screenshot below) when the extension is active.
2. Open a JS file, make some edits.
3. Hit Ctrl+S.

## Results
1. The file gets saved to disk (as expected).
2. The "Upload script" dialog is shown to the user.

![save-issue](https://user-images.githubusercontent.com/536464/27342286-0ebd41a6-55e0-11e7-86f6-aad9ec2f35ac.png)

## Expected Results
Ctrl+S is solely for saving files, nothing else should happen.

**Comment by bkircher** [comment]
Is this a bug or a feature? I am not sure anymore :smile:

**Comment by FabianTe** [comment]
Think of the eclipse plugin which uploads when you save a file (only if you configure it to)
The way I would use the vscode extension I wouldn't mind it uploading upons save (configurable of course)

**Comment by tineheller** [comment]
Uploading files automatically after Ctrl+S is a feature. Many people expect this feature because the eclipse plugin is doing the same thing.

**Comment by bkircher** [comment]
Since this is a "feature" I'll changed labels.

My point is that hitting Ctrl+S and having suddenly new behavior was very surprising to me.

I suggest that we keep this but change the default to off. So a user has to explicitly enable it in the workspace configuration or in the system configuration if he wants to upload or download scripts automatically on Save.

What are your opinions?

**Comment by FabianTe** [comment]
@bkircher I'd do it exactly as you said. Having it enabled by default would be dangerous for live systems. I only use the _auto-upload_ on development and testing environments because it's quicker. I'd add this setting into the `settings.json` If _auto-upload_ is disabled one would have to hit `ALT+F9` (Eclipse) or some other key combination.

**Comment by tineheller** [comment]
Ok, I agree with you. I don't like the auto-upload on default either. So I'll remove the dialog and only auto-upload javascript files that are set in settings.json.

So, if settings.json contains
`
"vscode-janus-debug.uploadOnSave": [
  "myScript1.js",
  "myScript2.js"
]
`
the scripts `myScript1.js` and `myScript2.js` will be uploaded automatically on save.

Is that ok?
Should I change the JSON schema?

**Comment by FabianTe** [comment]
@tineheller I'd only remove the dialog, if there was a command to add all scripts to that array. I wouldn't want to add dozens of scripts by hand.

Generally, why not have uploadOnSave be a boolean setting. When set to `true` every .js file that is saved **and not on an upload blacklist** would be auto-uploaded.

**Comment by idolum** [comment]
I agree as well. Having the auto-upload disabled by default is a good idea and I like also the idea by @FabianTe for activate the auto-upload in General with a blacklist. I don't expect the black list to be very long.

**Comment by tineheller** [comment]
Ok, just to be sure. I will add the boolean setting `uploadOnSave` and a list (like `disable-auto-upload`) where users can list JavaScript files. If `uploadOnSave` is set to true, every JavaScript file that is not on that list, will be uploaded automatically **without dialog**?

**Comment by tineheller** [comment]
I added a global flag `uploadOnSave` to `settings.json`. The flag is `true` on default. If the flag has changed, the extension must be restarted to get the changing. (96969a671f5b9f057f146d09810283ff66cc1190)
I would like to add a watcher for settings.json, then I can change the behaviour immediately if the flag has changed.

**Comment by tineheller** [comment]
I added the "never ask me again" option in the dialog. The flag is true on default so new users will get aware of the auto-upload. But it can be set to false immediately.
Done with c68c4e611593d9114c4b874d59981f229be3ec9e
