### ISSUE TITLE
Make all SDS connection timeouts configurable by the user

### ISSUE THREAD

**Issue by tineheller** [otris/vscode-janus-debug#51]
There is already `"sdsTimeout"` property in `launch.json` but it has no effect on Server Console, for instance.

**Comment by bkircher** [comment]
Actually, there are two timeout related properties: `"sdsTimeout"` and `"timeout"`. `"sdsTimeout"` seems to be used nowhere at all and `"timeout"` is just used for establishing some of the TCP connections.

I think we should remove `"sdsTimeout"` alltogether and use timeout for all network communication related stuff.

**Comment by tineheller** [comment]
sdsTimeout is used in node-documents-scripting. But it's ok we can just use `"timeout"` for all network communication timeouts.

**Comment by bkircher** [comment]
> sdsTimeout is used in node-documents-scripting.

That sounds weird. Why is node-documents-scripting using a file that is stored in the `.vscode` directory? Wasn't the point of that module to host the code that is independent of VS Code so that it can be re-used by other applications?

**Comment by tineheller** [comment]
> That sounds weird. Why is node-documents-scripting using a file that is stored in the .vscode directory? Wasn't the point of that module to host the code that is independent of VS Code so that it can be re-used by other applications?

Yes I know. But if you only use the node-documents-scripting you can use any launch.json file you want. You don't need a .vscode folder. I just want to save the login data in this module. But I don't want to invent a new file again...

**Comment by bkircher** [comment]
Done with PR #53
