### ISSUE TITLE
Get rid of code duplication in login.ts

### ISSUE THREAD

**Issue by bkircher** [otris/vscode-janus-debug#54]
`login.ts` still contains code that duplicates `config.ts`, especially `createLaunchJson` function. Needs to be removed.

**Comment by tineheller** [comment]
I think `createLaunchJson` in both files work very different. Only the variable initialConfigurations should be removed in login.ts.

**Comment by bkircher** [comment]
Jupp, you're correct. Just `initialConfigurations` and the comment string that goes at the top.
