### ISSUE TITLE
Conflicting declarations in portalScripting.d.ts

### ISSUE THREAD

**Issue by tineheller** [otris/vscode-janus-debug#63]
Some declarations in portalScripting.d.ts are also declared in other node modules. For example the variable `context` is also declared in the module `mocha` and the class `DOMException` is declared as `var` in module `typescript`.
This can cause a duplicate error in typescript compilation. Additional, it's not possible to get IntelliSense for the PortalScripting class `DOMException`.

**Comment by bkircher** [comment]
> the variable `context` is also declared in the module `mocha`

Is this really an issue? I am pretty sure you can't execute mocha tests on a DOCUMENTS server. mocha targets Node.js and browsers, only. It makes no sense to `require("mocha")` in a script that is written for DOCUMENTS.

**Comment by tineheller** [comment]
I'm not sure if this is an issue with mocha but it is with typescript. Some users want to use scripts that requires typescript (e.g. for using gulp tasks) and the DOCUMENTS scripts in the same VS Code project. There is no argument against using DOCUMENTS scripts together with any other scripts in the same VS Code project. For whatever reason. And it is possible to configure that. But you need to know how to configure it.
So at least this is a reason against just copying the portalScripting.d.ts file into the users' projects without asking them.

**Comment by tineheller** [comment]
Ok, I think the only way to solve this, is to ask VS Code to extend the typescript language server and to add our own target to the compiler options in jsconfig.json. Then this issue is duplicate to #45.
