### ISSUE TITLE
Global encryption flag

### ISSUE THREAD

**Issue by tineheller** [otris/vscode-janus-debug#64]
**Current State**
When a script is uploaded, the extension checks the encryption state on DOCUMENTS server. If the script is encrypted on server and the decryption pem is found on server, VS Code assumes, the script has been decrypted on download, so it will be encrypted on upload.
I think that's not the best way to handle encryption. Many cases have to be considered here, e.g. for customers, scripts are not decrypted on download.

**Suggested Change**
I would like to hand on the responsibility for encrypted scripts to the user and change the behaviour to something like this:

**Upload**
- If the script contains the `// #crypt` keyword, the script will be encrypted on upload.
- Additional I could add a global flag. If this flag is set, every script is encrypted on upload.

**Download**
- If the decryption pem is found on server and the script is encypted, the script is decrypted on download.

**Comment by idolum** [comment]
But this measn, I have to remove the `#crypt', if I want to upload a script unencrypted. It's seems dangerous to me, as you may forget to add it later when your work is done and you ship an unencrypted script to the customer by accident.

A flag, that allows me to deactivate the encryption for all scripts would be than the better option.

**Comment by tineheller** [comment]
**Changes**

1. It won't be possible anymore to download scripts in encrypted state, because there have been too many problems in keeping the source code and the encrypted-flag of a script consistent.
2. So the extension assumes that the source code of a script in VS Code is always unencrypted.
3. Scripts will be uploaded unencrypted on default and the encrypted-flag will be set to `false`.
4. If the flag `vscode-janus-debug.encryptOnUpload` is set to `true` scripts will be encrypted on upload and the encrypted-flag will be set to `true`.
5. For now it's not possible to upload scripts that are already encrypted in VS Code.

**Comment by tineheller** [comment]
Done with 635f661a4cd293e6722a0f1a779b0e563e439d4b
