### ISSUE TITLE
Upload scripts from folder not recursive

### ISSUE THREAD

**Issue by wehrstedt** [otris/vscode-janus-debug#72]
I would like to have the possibility to upload a folder recursivly. For now only the scripts inside the uploaded directory will be considered, scripts in sub-directories are ignored.

Example:
```
src    
    sub    
        subscript.js    
    script1.js
 ```
Uploading the "src" directory will only upload "script1.js".
Version: 0.0.8

**Comment by FabianTe** [comment]
If this was implemented it could also put the scripts in script category (https://github.com/otris/vscode-janus-debug/issues/40) matching the files parent folder. Example:

```
src    
    sub    
        sub.js    
        sub 2
            subsub.js
    normal.js
 ```

```sub.js``` would be in the script category **sub** and ```subsub.js``` would have the script category **sub 2**.

**Comment by wehrstedt** [comment]
That would be awesome!

**Comment by FabianTe** [comment]
This would have to be resolved in the node-documents-scripting project. If I did my homework right [this function] would have to be altered.

**Comment by tineheller** [comment]
Thanks @FabianTe! Yes, this is the function that has to be changed. And your changes look good to me at first sight. But as you said, it's recursion and async so I'd like to take a closer look at it. But this issue doesn't have first priority for now.

**Comment by wehrstedt** [comment]
I already had to deal with this problem in one of my projects, but I solved it using the await keyword for calling the function recursivly. If you like to see the code you can ask me.

**Comment by tineheller** [comment]
I won't have time before my holiday. But if you have experiences with it and have time to test it with many folders, you could create a pull request.

**Comment by tineheller** [comment]
In this issue only the recursive upload will be solved.
For the categories issue #40 will be used.
