### ISSUE TITLE
Exception when trying to upload without .vscode folder

### ISSUE THREAD

**Issue by derrohrbach** [otris/vscode-janus-debug#73]
I get the following exception when i try to "upload all files", if the `.vscode` folder is not existing:

`upload all failed: Error: ENOENT: no such file or directory, open 'c:\Users\marvi\Desktop\Projekte\AppScripts\.vscode\.documents-scripting-cache'`

### Steps to reproduce

1. Create a new folder
2. Open in VSCode
3. Create a new subfolder with some scripts
4. Try to upload that folder

### Possible fix

1. Create .vscode folder

### Details

**Version**: 0.0.8
**OS**: Windows 10 64-Bit

**Comment by tineheller** [comment]
Thanks for writing the issue.
Should be fixed with ec56da2dc3032b5af112cd6babb6269df1093896
