### ISSUE TITLE
What are the exact Typescript compiler options?

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#75]
As the title says. How is the typescript compiler for the to be to the DOCUMENTS server uploaded, compiled ts files configured? I want to compile ts to js on my own, without the plugin for now.

**Comment by bkircher** [comment]
Hi. Is your question about the compiler options when you upload TS to a DOCUMENTS server?

**Comment by FabianTe** [comment]
Yes

**Comment by tineheller** [comment]
The extension only uses the compiler option `--target "ES5"`
