### ISSUE TITLE
Provide Remote debugging for Typescript

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#76]
### Enhancement Request
Support remote Typescript debugging.

### Original issue
I wonder, is debugging a javascript compiled from a .ts file different from regular debugging?

If so, this might be relevant and this issue's label should be changed into 'enhancement': [Source Maps](http://www.aaron-powell.com/posts/2012-10-03-typescript-source-maps.html)

**Comment by bkircher** [comment]
> If so, this might be relevant [ ... ]: Source Maps

You're absolutely right. Debugging JS transpiled from TypeScript is not any different from debugging handwritten JS. The only thing we'd need are Source Maps in order to map JS source code positions to TypeScript source code positions.

**Comment by tineheller** [comment]
I tested the **source-map** module. With that module, it is simple to read source map files with the debugger.
This means, if the portal scripting source mapping works correctly, also for required scripts, it should be *relatively simple* to enable typescript debugging.

**Comment by tineheller** [comment]
The project was moved to gitlab
https://gitlab.otris.de/tools/vscode-janus-debug/issues/76
