### ISSUE TITLE
Plugin doesn't create .vscode folder if needed

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#77]
As the title says, the plugin does not create the folder _.vscode_ if it does not exist, but thorws this error:

![image](https://user-images.githubusercontent.com/7669818/28308618-1045aef0-6ba7-11e7-8635-722587a6ecb5.png)

# How to reproduce

_(This is only one possible scenario, there sure are other ways to recreate this)_

1. Create an empty folder and open it in vs code.
2. Create a .ts file
3. Open the Command Palette and start **Upload JS from TS file**

The error is displayed. **To fix this create the folder .vscode either manually or by setting vs code project specific settings (which created the folder for you)**

**Comment by tineheller** [comment]
It's the same problem as #73. Fix will probably be published tomorrow.
