### ISSUE TITLE
Typescript types conflicting with PortalScripting types

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#78]
*This issue isn't primarily about the vs code plugin but rather about the typescript -> javascript -> DOCUMENTS server topic*

# Issue

**The [portalScripting.d.ts typings file](https://github.com/otris/vscode-janus-debug/blob/master/portalscript/typings/portalScripting.d.ts) declares identifiers that are already defined by typescript:**

![image](https://user-images.githubusercontent.com/7669818/28312649-2a624804-6bb4-11e7-80a5-672a72934d7c.png)
*Censored content is not relevant for this issue*

My **tsconfig.json**:
```json
{
	"compilerOptions": {
		"target": "es5",
		"module": "none",
		"outDir": "dist"
	},
	"include": [
		"src/**/*.ts",
		"typings/**/*.d.ts"
	]
}
```

Vanilla tsc can still compile my .ts files but I don't know about the vs code plugin, couldn't test it yet.
This issue is more focused on the typings file itself. In a manual build pipeline like mine this is rather annoying.

# Workaround (use at own risk)
Add ```"skipLibCheck": true``` to your tsconfig.json:

```json
{
	"compilerOptions": {
		"target": "es5",
		"module": "none",
		"outDir": "dist",
		"skipLibCheck": true
	},
	"include": [
		"src/**/*.ts",
		"typings/**/*.d.ts"
	]
}
```
I'm unsure of the consequences though. The compiler will still thow errors concerning the main .ts files that contain my program code but I guess it won't check any libraries you'll be using.

**Comment by FabianTe** [comment]
Where is the typings file from? I could correct it according to the newest PortalScripting API Documentation (that I have got) while I working with it.

**Comment by tineheller** [comment]
Duplicate to #63

**Comment by tineheller** [comment]
The dubplicate Issue (#63) is closed. But this problem still exists. Not only for compiling TypeScript files but also for IntelliSense. The interfaces of the dublicate symbols can be extended but then we'll get IntellliSense for members that we cannot use on the DOCUMENTS server.
At least it seems we are not the only ones with that problem and it's a well known issue. I added a workaround for this problem to our wiki ([lib.d.ts](https://github.com/otris/vscode-janus-debug/wiki/IntelliSense-for-PortalScripting#libdts)) but I'm still hoping to find a better way.

**Comment by tineheller** [comment]
The problem and some ways to deal with it is described here
https://github.com/otris/vscode-janus-debug/wiki/IntelliSense-for-PortalScripting
I don't think that there's a better way for now.
