### ISSUE TITLE
Provide hotkeys for uploading/running/downloading scripts

### ISSUE THREAD

**Issue by mpdrescher** [otris/vscode-janus-debug#84]
It would be nice to have default hotkeys for frequently used commands such as (and not limited to):
- run script
- upload script
- upload and run script

(current version: v.0.0.8)

Edit: Changed hotkeys to default hotkeys, since it is no problem to manually add or change them.

**Comment by FabianTe** [comment]
Also

- Uploade JS from TS
- Upload folder *xyz*

Where *xyz* is a folder configured earlier like the src folder. (This might be a seperate feature)

**Comment by bkircher** [comment]
With hotkeys you mean  keyboard shortcuts you can assign to a command in the palette, right?

**Comment by mpdrescher** [comment]
Yes

**Comment by bkircher** [comment]
Do you have any suggestions or preferences for those? Bear in mind that there are already standard shortcuts that we shouldn't give a new meaning (like Ctrl+S).

**Comment by FabianTe** [comment]
Maybe the eclipse shortcuts are free, haven't checked it though. They were ALT + F9 and so on I believe.

**Comment by mpdrescher** [comment]
I currently have

M-s -> run
M-x -> upload + run
M-u -> upload
M-j -> js from ts

All of those are free in the vanilla vscode, but they may be taken by other plugins due to their simplicity.

**Comment by FabianTe** [comment]
M?

**Comment by mpdrescher** [comment]
Meta/Alt

**Comment by bkircher** [comment]
Done with f4cc4c3
