### ISSUE TITLE
Import/Export PortalScripts and FileTypes as XML

### ISSUE THREAD

**Issue by tineheller** [otris/vscode-janus-debug#86]
VS Code should provide commands for the XML import/export for PortalScript files.

Scripts cannot be downloaded in encrypted state anymore (see #64). To get encrypted scripts that cannont be decrypted, or to move them between different DOCUMENTS servers, the XML export/import has to be used.

**Comment by FabianTe** [comment]
I'd like to propose to extend that to include every DOCUMENTS structure that may be exported / imported via XML (file types, folders, ...)

**Comment by tineheller** [comment]
after finishing some work in [node-sds](https://github.com/otris/node-sds) the XML import/export will be implemented, but first only for JavaScript files

**Comment by tineheller** [comment]
First step:
Simple command **Export XML ...** implemented (only command palette (**F1**) for now).
You can select **DlcFileType** or **PortalScript**:
* **DlcFileTypes**: generates the xml file containing all filetypes to a subfolder `fileTypes`
* **PortalScripts**: generates the xml file containing all portal scripts to a subfolder `portalScripts`

First step will be available in next version (1.0.17).

Next step:
* After selecting the class (**DlcFileType** or **PortalScript**) you will get a list for selecting a single filetype or portal script.

Later it will be possible to define a subset of all filetypes or portal scripts. Maybe by using a `.json` file that can be inserted into the xml folder.

Also the folder names will be configurable.

**Comment by tineheller** [comment]
If a filetype contains documents templates, the links are inserted into the xml but the **Export XML ...** command cannot download them yet.

**Comment by tineheller** [comment]
In version 1.0.19, you can select a file type name or a portal script name or you can choose **All in one file** or **All in seperate files**.
There's also an [entry in wiki](https://github.com/otris/vscode-janus-debug/wiki/XML-Export).

**Comment by tineheller** [comment]
With version 1.0.30 it is also possible to get any subset of portal scripts or file types, if the names are listed in an arbitrary json file. See [wiki entry](https://github.com/otris/vscode-janus-debug/wiki/XML-Export).

**Comment by tineheller** [comment]
Export PortalScripts and FileTypes as XML is implemented.
For Import XML or Import/Export other DOCUMENTS structures, a new issue with use cases should be created on [GitLab](https://gitlab.otris.de/tools/vscode-janus-debug/issues).
