### ISSUE TITLE
Remove script settings from settings.json

### ISSUE THREAD

**Issue by tineheller** [otris/vscode-janus-debug#90]
At the moment any settings concerning DOCUMENTS scripts can be set in `settings.json`. But actually in `settings.json` are only VS Code settings. So it's better to move the script settings from `settings.json` to `documents-scripting-settings.json` or `vscode-janus-debug-settings.json`.

**Comment by FabianTe** [comment]
As I wrote on some other issue before, I'd create a central folder, maybe inside the ```.vscode``` folder that holds all config files, cache files, and stored passwords from this plugin.

In my current project folder for example I have an empty ```documents-scripting-settings.json``` and I think that a standard plugin user not involved in the dev of this plugin might also wonder "Why is there an empty ```.documents-scripting-cache``` file in my vscode folder.

![image](https://user-images.githubusercontent.com/7669818/28559832-7bd37f28-7118-11e7-972e-e7cc33f4e9b5.png)

**Comment by tineheller** [comment]
For the time being the extension settings in settings.json will not be moved to another file. VS Code supports a good API for accessing the settings in settings.json and so for now I think it's the easiest way just to use this API. If there is a good reason for using a different file one day, a new issue will be created.
