### ISSUE TITLE
Show #import scripts

### ISSUE THREAD

**Issue by tineheller** [otris/vscode-janus-debug#92]
If a script is open in DOCUMENTS Manager, you can show the source code of the script and of all #import scripts in one file in an editor by pressing 'Ctrl + D'.
It would be nice to have this feature in the Extension.

**Comment by wehrstedt** [comment]
Is it possible to teach vs code to interpret the import statements as a "real" import statement? Then you could press "ctrl" and click on the script name and vscode would open the script, like when you press "ctrl" and click on a function name or a variable

**Comment by tineheller** [comment]
Actually that would be nice. But I'm not sure. Maybe that gets us again to the language server.

**Comment by tineheller** [comment]
Command **Show Imports** was inserted. It shows the source code of the script and all imports in the console output window. (You get the same output by 'Ctrl + D' in DOCUMENTS Manager.) DOCUMENTS \#8047 is required for this feature.
