### ISSUE TITLE
Typings file source

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#93]
Hi guys,

where does the Typings file originate from? Is this auto generated? I found some wrong parameter options and I'd like to change these.

**Comment by tineheller** [comment]
Yes it's generated. I opened a new issue, because there might be more problems. See #94.

**Comment by FabianTe** [comment]
So I guess there is no way i can contribute to it?

**Comment by tineheller** [comment]
No sorry. Please just write the wrong parameter options to #94 or create a new issue then I will fix it.
