### ISSUE TITLE
Upload and Run multiple files at once (from Folder)

### ISSUE THREAD

**Issue by mpdrescher** [otris/vscode-janus-debug#96]
Having an option "Upload and Run Scripts from Folder" would simplify running all test cases of a module at once to see if everything is ok.
The option "Upload Scripts from Folder" already exists, but doesn't execute the scripts once they are uploaded.
Similar to "Upload Scripts from Folder", "Upload and Run Scripts from Folder" could be available from the context menu.

(on v.0.0.9)

**Comment by FabianTe** [comment]
Off-Topic: Sometimes I wonder how awesome it would be to have mocha tests in DOCUMENTS :smile: With this you would just have to retrieve all scripts return values and test them somehow....
On-Topic: This might be a rather *specific* feature to use. I guess I wouldn't need it that mutch :wink:

**Comment by tineheller** [comment]
Uploading and running multiple scripts at once should rather be done automatically with a suitable test environment. This extension is not optimized for tests. It only supports features to make the development of scripts more comfortable. To add features for automatic tests to this extension would overload it. So for automatic tests some of the other ways for uploading and executing scripts on Documents should be used.
