### ISSUE TITLE
Upload Script - Check Changes

### ISSUE THREAD

**Issue by mweiss237** [otris/vscode-janus-debug#97]
Hi,

wouldn't it be nice to check if a script on the DOCUMENTS server has changed since my last up-/download in VS Code before my script is transferred to the server?
The reason for this is that I don't want to overwrite the script-changes, that my colleagues made in DOCUMENTS server directly.

**Comment by tineheller** [comment]
If you add the following entry to your `.vscode/settings.json`
```
    "vscode-janus-debug.conflictMode": [
        "test1",
        "test2",
    ],
```
the scripts `test1.js` and `test2.js` will be checked on upload. If they have been changed on the server since the last up- or download, you should get an error message.

**Comment by tineheller** [comment]
The behaviour will be changed here. The conflict mode will be the default state.

**Comment by tineheller** [comment]
With 96bc7d3862fa69d62a697eed823ea1c0a9e25e19 and c45e891072b59a4366e78dee4a1c8bb6fec915a6 the conflict mode will be the default state for all scripts.
The list `vscode-janus-debug.conflictMode` in `.vscode/settings.json` was replaced by `vscode-janus-debug.forceUpload`. In this list you can insert scripts that should not be checked on upload.
