### ISSUE TITLE
PortalScripting typings are missing constructor for ScriptCall

### ISSUE THREAD

**Issue by derrohrbach** [otris/vscode-janus-debug#98]
As the title states, the typings are missing the constructor for ScriptCall

From the Portalscript API: 
`ScriptCall ScriptCall::new ( Var systemUser, String scriptName, Boolean waitable )`

See: [ScriptCall typings](https://github.com/otris/vscode-janus-debug/blob/master/portalscript/typings/portalScripting.d.ts#L6025)

Maybe this happens because the contructor is called `new` instead of `contructor` in the documentation

**Comment by tineheller** [comment]
Ok, thanks for the issue! I fixed the documentation and generated a new `d.ts` file. It will come with the next version or you can download it from github. I will commit it now.
